mutation Siginin($email: String = "multi@multisolution.art.br", $password: String = "multi") {
  signIn(email: $email, password: $password)
}

query AllUsers {
  allUsers {
    id
    email
  }
}

mutation DeleteUser($input: String = "5dc2e670e3523") {
  deleteUser(id: $input)
}
