name: API

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate
      working-directory: ./api

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      working-directory: ./api

    - name: Run test suite
      run: composer test
      working-directory: ./api

    - name: Docker build and push
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      working-directory: ./api
      run: |
        docker build . -t registry.multisolution.art.br/multi:api
        docker push registry.multisolution.art.br/multi:api
