name: WEB

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm ci
        npm test
      working-directory: ./web
      env:
        CI: true

    - uses: Azure/docker-login@v1
      with:
        login-server: registry.multisolution.art.br
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    
    - name: Docker build and push  
      working-directory: ./web
      run: |
        docker build . -t registry.multisolution.art.br/multi:web
        docker push registry.multisolution.art.br/multi:web
        
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MULTI_HOST }}
        username: ${{ secrets.MULTI_USER }}
        key: ${{ secrets.MULTI_KEY }}
        port: ${{ secrets.MULTI_PORT }}
        script: cd multi && docker-compose pull web && docker-compose up -d web
